import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/utils";
import { Provider } from "@/components/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Buildwise",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex flex-col min-h-dvh  justify-center`}
      >
        <Provider session={session}>
          {children}
          <Toaster
            toastOptions={{
              error: {
                duration: 8000,
                className: "border border-red-400",
              },
              success: {
                duration: 8000,
                className: "border border-green-400",
              },
            }}
          />
        </Provider>
      </body>
    </html>
  );
}
